# Generated by Django 4.2.11 on 2024-03-20 06:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BigCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='大カテゴリ名')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='タグ名')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日')),
            ],
        ),
        migrations.CreateModel(
            name='SmallCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='小カテゴリ名')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tblog.bigcategory', verbose_name='大カテゴリ')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='タイトル')),
                ('text', models.TextField(verbose_name='本文')),
                ('thumbnail', models.ImageField(blank=True, upload_to='thumbnail/', verbose_name='サムネイル')),
                ('is_publick', models.BooleanField(default=True, verbose_name='公開可能か?')),
                ('is_html', models.BooleanField(default=False, verbose_name='HTMLソースか?')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tblog.smallcategory', verbose_name='カテゴリ')),
                ('tag', models.ManyToManyField(blank=True, to='tblog.tag', verbose_name='タグ')),
            ],
        ),
    ]
